# Generated by Django 4.2.16 on 2024-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
